# Use a Cypress image with Node included
FROM cypress/included:15.0.0

WORKDIR /app

# Copy package.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project
COPY . .

# Run Cypress test
CMD ["npx", "cypress", "run", "--spec", "cypress/e2e/common.cy.js"]

