#!/bin/bash

mkdir Cities
cd Cities

printf "%-12s %-12s %-12s %-12s %-12s %-12s\n" "Bethlehem" "77368" "Beth22" "02" "George" "123" > Bethlehem.txt
printf "%-12s %-12s %-12s %-12s %-12s %-12s\n" "Ramallah" "158496" "Ram33" "03" "Hasan" "123" > Ramallah.txt
printf "%-12s %-12s %-12s %-12s %-12s %-12s\n" "Jerusalem" "874362" "Je1" "04" "Alex" "789" > Jerusalem.txt
printf "%-12s %-12s %-12s %-12s %-12s %-12s\n" "Nablus" "89632" "Na89" "05" "Khader" "789" > Nablus.txt
printf "%-12s %-12s %-12s %-12s %-12s %-12s\n" "Hebron" "47896" "He9" "06" "Ramzi" "789" > Hebron.txt

echo -n "Number of files containing the letter 'e' in their names: "
ls | grep -c -i "e"

printf "%-12s %-12s %-12s %-12s %-12s %-12s\n" "City" "Population" "CityCode" "PhoneCode" "FamousPerson" "AreaCode" > all_cities.txt
cat Bethlehem.txt Ramallah.txt Jerusalem.txt Nablus.txt Hebron.txt >> all_cities.txt

echo "content of all_cities.txt:"
cat all_cities.txt
echo

echo "Cities with the lowest and highest population:"
tail -n +2 all_cities.txt | tr -s " " | cut -d " " -f1-2 | sort -k 2 -n | sed -n '1p;$p' | cut -d " " -f1 | sed -n '1s/^/Lowest: /p;2s/^/Highest: /p'
echo

echo "Cties and their city codes:"
tr -s " " < all_cities.txt | cut -d " " -f1,3
echo

echo "City with phone code = 04:"
tr -s " " < all_cities.txt | cut -d " " -f1,4 | grep -w "04" | cut -d " " -f1
echo

echo "Cities sorted by phone code:"
tr -s " " < all_cities.txt | cut -d " " -f1,4 | sort -k 2 -n
echo

echo " Famous person in Hebron:"
tr -s " " < all_cities.txt | grep "Hebron" | cut -d " " -f5
echo

echo "Cities with area code 123:"
tr -s " " < all_cities.txt | cut -d " " -f1,6 | grep -w "123" | cut -d " " -f1
echo

echo "Area code for Nablus:"
tr -s " " < all_cities.txt | grep "Nablus" | cut -d " " -f6
echo

echo "Erasing all created files and folders.."
cd ..
rm -rf Cities
